on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bcdevices/zephyr:latest
    name: Build
    steps:
      - name: Install Dependencies
        run: |
          apt-get update;
          apt-get install --yes --no-install-recommends \
            nodejs \
            zstd

      - name: Checkout
        uses: actions/checkout@v3

      - name: Link Directories
        run: |
          ln -s /usr/src/zephyr-3.4.0/.west .west
          ln -s /usr/src/zephyr-3.4.0/modules modules
          ln -s /usr/src/zephyr-3.4.0/tools tools
          ln -s /usr/src/zephyr-3.4.0/zephyr zephyr
          ln -s /usr/src/zephyr-3.4.0/bootloader bootloader

      - name: Hash west modules
        id: hash-west
        run: |
          FILE_PATH=zephyr/west.yml
          HASH="$(sha256sum <(find . -name build.yml -o -name west.yml -type f -exec sha256sum \; | sort) | head -c 64)"
          echo "hash=$HASH" >> "$GITHUB_OUTPUT"
          echo "computed hash: $HASH"

      - name: Cache west modules
        uses: actions/cache@v3
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ steps.hash-west.outputs.hash }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
        timeout-minutes: 5
        continue-on-error: true

      - name: Clone ZMK
        run: git clone --depth 1 git@github.com:zmkfirmware/zmk.git

      - name: West Update
        run: west update

      - name: West Zephyr export
        run: west zephyr-export

      - name: West Build (Corne Left)
        run: west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=corne_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Corne Left Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"

      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 corne_left_nice_nano_v2.uf2

      - name: West Build (Corne Right)
        run: west build --pristine -s zmk/app -b nice_nano_v2 -- -DSHIELD=corne_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Corne Right Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"

      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 corne_right_nice_nano_v2.uf2

      - name: Zip Artifacts
        run: zip firmware.zip corne_left_nice_nano_v2.uf2 corne_right_nice_nano_v2.uf2

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: firmware.zip
          name: firmware.zip

      - name: Hash west modules
        id: hash-west
        run: |
          FILE_PATH=zephyr/west.yml
          HASH=$(sha256sum <(find . -name build.yml -o -name west.yml -type f -exec sha256sum \; | sort) | head -c 64)
          echo "hash=$HASH" >> "$GITHUB_OUTPUT"
          echo "computed hash: $HASH"
