on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build
    steps:
      - name: Install Dependencies
        run: |
          apt-get update;
          apt-get install --yes --no-install-recommends \
            nodejs \
            zip \
            openssl \
            ca-certificates

      - name: Checkout
        uses: actions/checkout@v3

      - name: West Init
        run: west init -l config

      - name: West Update
        run: west update

      - name: West Zephyr export
        run: west zephyr-export

      - name: West Build (Corne Left)
        run: west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=corne_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Corne Left Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"

      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 corne_left_nice_nano_v2.uf2

      - name: West Build (Corne Right)
        run: west build --pristine -s zmk/app -b nice_nano_v2 -- -DSHIELD=corne_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Corne Right Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"

      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 corne_right_nice_nano_v2.uf2
          
      - name: Zip Artifacts
        run: zip firmware.zip corne_left_nice_nano_v2.uf2 corne_right_nice_nano_v2.uf2

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: firmware.zip
          if-no-files-found: ignore
